### ISSUE TITLE
What is this repository for?

### ISSUE THREAD

**Issue by DimaSheiko** [hippuli/TradeSkillMaster#1]
What is this repository for? Is it a modified or improved version of the original? For a private server? I've been seeing for several days that updates the repository while making updates to the original addon. What is the purpose?

**Comment by hippuli** [comment]
It is 1:1 copy from curse repackaged the right way for WowUp compatibility. I won't do any modifications or improvements. They are for my personal use but of course available for everyone.

**Comment by DimaSheiko** [comment]
Maybe you should make it private.
